In [35]:
import pandas as pd

In [36]:
#Load data
df=pd.read_csv('Wine_data.csv')
#to get data from staring
df.head()
#to get data from end
df.tail(3)

#to get random record
df.sample(5, ignore_index=True)

#To check dimension of the dataframe
df.ndim

#to check size of data
df.size

#To get column name
df.columns

#To get basic info of data
df.info()

#to get description of the data
df.describe(include="all")

<class 'pandas.DataFrame'>
RangeIndex: 220 entries, 0 to 219
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         220 non-null    float64
 1   volatile acidity      220 non-null    float64
 2   citric acid           220 non-null    float64
 3   residual sugar        220 non-null    float64
 4   chlorides             220 non-null    float64
 5   free sulfur dioxide   220 non-null    float64
 6   total sulfur dioxide  220 non-null    float64
 7   density               220 non-null    float64
 8   pH                    220 non-null    float64
 9   sulphates             220 non-null    float64
 10  alcohol               220 non-null    float64
 11  quality               220 non-null    int64
 12  Id                    220 non-null    int64
 13  name                  220 non-null    str
 14  date                  220 non-null    str
dtypes: float64(11), int64(2), str(2)
memory usage: 25.9 KB

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,name,date
count,220.000000,220.000000,220.000000,220.000000,220.000000,220.000000,220.000000,220.000000,220.000000,220.000000,220.000000,220.000000,220.00000,220,220
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,220,204
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WineA,2024-04-12
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,3
mean,9.846318,0.419500,0.463364,2.131818,0.075709,18.523182,41.631818,0.996850,3.280318,0.773227,10.836500,6.063636,112.95000,NaN,NaN
std,1.021658,0.092308,0.119419,0.783614,0.012261,6.388950,16.264301,0.001209,0.105287,0.073999,0.696398,1.062239,62.86575,NaN,NaN
min,7.500000,0.170000,0.160000,0.800000,0.044000,3.000000,10.000000,0.993880,2.970000,0.580000,8.880000,3.000000,5.00000,NaN,NaN
25%,9.177500,0.360000,0.390000,1.600000,0.067750,14.075000,28.925000,0.996090,3.210000,0.720000,10.362500,5.000000,58.75000,NaN,NaN
50%,9.840000,0.420000,0.470000,2.100000,0.076000,18.450000,40.400000,0.996875,3.280000,0.775000,10.850000,6.000000,113.50000,NaN,NaN
75%,10.580000,0.480000,0.542500,2.700000,0.084250,22.325000,51.050000,0.997630,3.350000,0.820000,11.322500,7.000000,167.25000,NaN,NaN
max,12.800000,0.690000,0.780000,4.100000,0.104000,37.900000,103.000000,1.000340,3.540000,0.960000,12.700000,8.000000,220.00000,NaN,NaN

In [37]:
df.name

0                                WineA
1                                WineB
2                                WineC
3                                WineD
4            Weingut Syrah Reserve 575
                    ...
215           Bodega Pinot Classic 513
216       Castello Merlot Grand Cru 41
217    Bodega Chardonnay Grand Cru 257
218       Chateau Cabernet Special 857
219       Bodega Sauvignon Classic 591
Name: name, Length: 220, dtype: str

In [38]:
df.name.str.title()

0                                Winea
1                                Wineb
2                                Winec
3                                Wined
4            Weingut Syrah Reserve 575
                    ...
215           Bodega Pinot Classic 513
216       Castello Merlot Grand Cru 41
217    Bodega Chardonnay Grand Cru 257
218       Chateau Cabernet Special 857
219       Bodega Sauvignon Classic 591
Name: name, Length: 220, dtype: str

In [39]:
df.name.str.len()

0       5
1       5
2       5
3       5
4      25
       ..
215    24
216    28
217    31
218    28
219    28
Name: name, Length: 220, dtype: int64

In [40]:
df[df.name.str.contains('a')]

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,name,date
4,9.91,0.45,0.49,2.8,0.053,21.9,60.5,0.99683,3.31,0.90,8.88,4,5,Weingut Syrah Reserve 575,2023-02-12
5,8.72,0.56,0.34,0.8,0.059,22.3,59.8,0.99571,3.35,0.79,9.79,4,6,Bodega Riesling Special 559,2024-05-09
6,9.54,0.61,0.41,3.1,0.064,23.5,51.8,0.99716,3.32,0.73,9.15,4,7,Domaine Pinot Grand Cru 285,2022-01-14
7,9.08,0.63,0.49,1.1,0.072,18.1,42.5,0.99795,3.20,0.81,8.88,3,8,Domaine Riesling Premium 349,2023-07-24
8,8.88,0.44,0.40,2.9,0.079,15.3,43.6,0.99742,3.42,0.79,10.84,5,9,Domaine Cabernet Classic 105,2022-07-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
215,10.62,0.38,0.41,3.0,0.072,24.8,55.7,0.99732,3.16,0.79,10.99,6,216,Bodega Pinot Classic 513,2024-10-08
216,10.21,0.17,0.60,2.5,0.059,13.7,21.2,0.99388,3.21,0.72,11.25,7,217,Castello Merlot Grand Cru 41,2024-06-03
217,11.29,0.36,0.46,2.8,0.082,26.6,40.2,0.99651,3.27,0.84,11.24,7,218,Bodega Chardonnay Grand Cru 257,2022-02-22
218,9.21,0.36,0.51,2.6,0.082,10.3,19.6,0.99854,3.20,0.70,11.09,6,219,Chateau Cabernet Special 857,2022-02-12
219,10.02,0.21,0.47,1.8,0.050,17.2,33.5,0.99676,3.04,0.70,11.37,7,220,Bodega Sauvignon Classic 591,2022-03-24

In [42]:
#date and time operation
df.date.dtype

In [44]:
df['date']=pd.to_datetime(df.date)

In [47]:
df.date.dtype

dtype('<M8[us]')

In [50]:
df['date']=pd.to_datetime(df.date)
df['Year']=df.date.dt.year
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 220 entries, 0 to 219
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         220 non-null    float64
 1   volatile acidity      220 non-null    float64
 2   citric acid           220 non-null    float64
 3   residual sugar        220 non-null    float64
 4   chlorides             220 non-null    float64
 5   free sulfur dioxide   220 non-null    float64
 6   total sulfur dioxide  220 non-null    float64
 7   density               220 non-null    float64
 8   pH                    220 non-null    float64
 9   sulphates             220 non-null    float64
 10  alcohol               220 non-null    float64
 11  quality               220 non-null    int64
 12  Id                    220 non-null    int64
 13  name                  220 non-null    str
 14  date                  220 non-null    datetime64[us]
 15  year                  220 non-null    datetime64[us]
 16  Year                  220 non-null    int32
dtypes: datetime64[us](2), float64(11), int32(1), int64(2), str(1)
memory usage: 28.5 KB

ADD new Date

In [51]:
df.loc[5]

fixed acidity                                  8.72
volatile acidity                               0.56
citric acid                                    0.34
residual sugar                                  0.8
chlorides                                     0.059
free sulfur dioxide                            22.3
total sulfur dioxide                           59.8
density                                     0.99571
pH                                             3.35
sulphates                                      0.79
alcohol                                        9.79
quality                                           4
Id                                                6
name                    Bodega Riesling Special 559
date                            2024-05-09 00:00:00
year                            2024-05-09 00:00:00
Year                                           2024
Name: 5, dtype: object

In [54]:
df.loc[len(df)]=[8.2,0.55,0.43,0.9,0.02,21.3,58,0.89,3.31,0.8,0.78,9.78,4,7,"abc","2024-05-09","2024"]

In [56]:
df.tail(1)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,name,date,year,Year
220,8.2,0.55,0.43,0.9,0.02,21.3,58.0,0.89,3.31,0.8,0.78,9.78,4,7,abc,2024-05-09,2024

Create new column

In [57]:
df['High_alcoh']=df.alcohol>=10
df.head(1)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,name,date,year,Year,High_alcoh
0,8.5,0.28,0.56,1.8,0.092,35.0,103.0,0.9969,3.3,0.75,10.5,7.0,16,WineA,2023-01-10 00:00:00,2023-01-10 00:00:00,2023,True

In [58]:
df['wine_type']='red wine'
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,name,date,year,Year,High_alcoh,wine_type
0,8.50,0.28,0.56,1.8,0.092,35.0,103.0,0.99690,3.30,0.75,10.50,7.0,16,WineA,2023-01-10 00:00:00,2023-01-10 00:00:00,2023,True,red wine
1,8.00,0.59,0.16,1.8,0.065,3.0,16.0,0.99620,3.42,0.92,10.50,7.0,128,WineB,2023-02-15 00:00:00,2023-02-15 00:00:00,2023,True,red wine
2,9.60,0.32,0.47,1.4,0.056,9.0,24.0,0.99695,3.22,0.82,10.30,7.0,200,WineC,2023-03-20 00:00:00,2023-03-20 00:00:00,2023,True,red wine
3,12.80,0.30,0.74,2.6,0.095,9.0,28.0,0.99940,3.20,0.77,10.80,7.0,205,WineD,2023-04-25 00:00:00,2023-04-25 00:00:00,2023,True,red wine
4,9.91,0.45,0.49,2.8,0.053,21.9,60.5,0.99683,3.31,0.90,8.88,4.0,5,Weingut Syrah Reserve 575,2023-02-12 00:00:00,2023-02-12 00:00:00,2023,False,red wine

Merge and concat

In [59]:
data1={
    'Name':['A','B','C'],
    'age':[23,25,67],
    'salary':[1000,2000,3000]
}
data2={
    'Name':['A','BB','C'],
    'age':[23,23,67],
    'salary':[1000,2300,3000]
}

In [60]:
new_df1=pd.DataFrame(data1)
new_df2=pd.DataFrame(data2)

In [61]:
new_df1.head()

  Name  age  salary
0    A   23    1000
1    B   25    2000
2    C   67    3000

In [63]:
pd.concat([new_df1,new_df2])

  Name  age  salary
0    A   23    1000
1    B   25    2000
2    C   67    3000
0    A   23    1000
1   BB   23    2300
2    C   67    3000

In [64]:
pd.concat([new_df1,new_df2],ignore_index=True)

  Name  age  salary
0    A   23    1000
1    B   25    2000
2    C   67    3000
3    A   23    1000
4   BB   23    2300
5    C   67    3000

In [69]:
#column-wise concatinate by using axis=1 
new_def=pd.concat([new_df1,new_df2],ignore_index=True,axis=0)
new_def

  Name  age  salary
0    A   23    1000
1    B   25    2000
2    C   67    3000
3    A   23    1000
4   BB   23    2300
5    C   67    3000

In [70]:
new_def.drop_duplicates(inplace=True)
new_def.head()

  Name  age  salary
0    A   23    1000
1    B   25    2000
2    C   67    3000
4   BB   23    2300

***Merge***

In [73]:
new_df1.head()

  Name  age  salary
0    A   23    1000
1    B   25    2000
2    C   67    3000

In [72]:
new_df2.head()

  Name  age  salary
0    A   23    1000
1   BB   23    2300
2    C   67    3000

In [74]:
pd.merge(new_df1,new_df2,how='outer')

  Name  age  salary
0    A   23    1000
1    B   25    2000
2   BB   23    2300
3    C   67    3000